### ISSUE TITLE
Resolv cannot resolve address if `resolv.conf` first `nameserver` answers with `SERVFAIL` 

### ISSUE THREAD

**Issue by BobSilent** [ruby/resolv#23]
in a docker container environment my containers get created with the following `resolv.conf`

```
nameserver 172.24.160.1
nameserver 10.81.32.106
nameserver 10.81.32.104
```

the first one is the gateway machine which cannot resolve any internet names.

nslookup and ping are able to resolve address:
```bash
# nslookup google.com
;; Got SERVFAIL reply from 172.24.160.1, trying next server
Server:         10.81.32.106
Address:        10.81.32.106#53

Non-authoritative answer:
Name:   google.com
Address: 142.250.185.206
;; Got SERVFAIL reply from 172.24.160.1, trying next server
Name:   google.com
Address: 2607:f8b0:4006:80e::200e

# ping google.com
PING google.com (142.250.65.174) 56(84) bytes of data.
```

but `resolv` fails:
```ruby
irb(main):001:0> require 'resolv'
=> true
irb(main):002:0> Resolv.getaddresses "google.com"
=> []
irb(main):003:0> Resolv.getaddress "google.com"
Traceback (most recent call last):
        21: from ./.bundle/bin/irb:27:in `<main>'
        20: from ./.bundle/bin/irb:27:in `load'
        19: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
         2: from (irb):3:in `<main>'
         1: from /usr/local/lib/ruby/2.7.0/resolv.rb:44:in `getaddress'
/usr/local/lib/ruby/2.7.0/resolv.rb:94:in `getaddress': no address for google.com (Resolv::ResolvError)
```

**Comment by BobSilent** [comment]
@hsbt what can I do here to get this merged?
